"""Emit LaTeX table bodies for the supporting experiments, straight from
results/*.json, so no number in the manuscript is transcribed by hand.

Writes paper/tables_auto.tex, which cas_calmnet.tex \input{}s. Re-run after any
new result lands:

    cd src && python make_tables.py
"""
from __future__ import annotations
import json
import statistics as st
from pathlib import Path

RESULTS = Path(__file__).resolve().parent.parent / "results"
OUT = Path(__file__).resolve().parent.parent / "paper" / "tables_auto.tex"
BS = chr(92)
NL = chr(10)


def L(name):
    p = RESULTS / name
    if not p.exists():
        return {}
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except Exception:
        return {}


def acc(v):
    return v.get("acc") if isinstance(v, dict) else None


def agg(files, keyfn):
    """Collect accuracies across files into {key: [values]}."""
    out = {}
    for f in files:
        for k, v in L(f).items():
            a = acc(v)
            if a is None:
                continue
            out.setdefault(keyfn(k), []).append(a)
    return out


def tbl(label, caption, colspec, header, rows, small=False):
    L_ = []
    L_.append(BS + "begin{table}[t]")
    L_.append(BS + "caption{" + caption + "}")
    L_.append(BS + "label{" + label + "}")
    L_.append(BS + "centering")
    if small:
        L_.append(BS + "small")
    L_.append(BS + "begin{tabular}{" + colspec + "}")
    L_.append(BS + "toprule")
    L_.append(header + " " + BS + BS)
    L_.append(BS + "midrule")
    L_ += rows
    L_.append(BS + "bottomrule")
    L_.append(BS + "end{tabular}")
    L_.append(BS + "end{table}")
    return NL.join(L_) + NL + NL


def bold(x):
    return BS + "textbf{" + x + "}"


def main():
    out = ["%% Generated by src/make_tables.py -- do not edit by hand." + NL + NL]

    # ---------------- temporal smoothing, 4 seeds, with shuffle control
    files = ["temporal_ds007788ctrl.json"] + [
        "temporal_ds007788ctrl_seed%d.json" % i for i in (1, 2, 3)]
    a = agg(files, lambda k: k)
    order = [("w2.0|none", "no smoothing", "baseline"),
             ("w2.0|forward", "HMM forward filter", "causal"),
             ("w2.0|forward@0.5", "forward, $%s%s=0.5$" % (BS, "tau"), "causal"),
             ("w2.0|viterbi", "Viterbi decoding", "non-causal"),
             ("w2.0|fwdshuf", "forward on shuffled order", bold("control"))]
    base = st.mean(a["w2.0|none"])
    rows = []
    for k, lab, kind in order:
        if k not in a:
            continue
        vs = a[k]
        m, s = st.mean(vs), (st.stdev(vs) if len(vs) > 1 else 0.0)
        d = m - base
        ds = "---" if k == "w2.0|none" else "%+.3f" % d
        if k == "w2.0|fwdshuf":
            ds = bold(ds)
        rows.append("%s & %s & %d & %.3f $%spm$ %.3f & %s %s" %
                    (lab, kind, len(vs), m, BS, s, ds, BS + BS))
    out.append(tbl(
        "tab:temporal",
        "Temporal smoothing on cohort A, mean $" + BS + "pm$ SD over 4 seeds. "
        "The control applies the same filter after shuffling window order: it "
        "does not merely lose the gain, it falls 0.113 below the unsmoothed "
        "baseline, so the benefit comes from genuine temporal structure and "
        "not from the smoothing operation.",
        "llrrr", "Method & Causality & $n$ & Bal. acc. & $" + BS + "Delta$",
        rows))

    # ---------------- SPDNet alignment variants, 3 seeds
    a = agg(["spdnet.json"], lambda k: k.split("|")[0])
    names = {"aspd_ea": "Euclidean Alignment (fixed)",
             "aspd_learn": "learned alignment",
             "aspd_noalign": bold("no alignment")}
    rows = []
    for k in ("aspd_ea", "aspd_learn", "aspd_noalign"):
        if k not in a:
            continue
        vs = a[k]
        rows.append("%s & %d & %.3f $%spm$ %.3f & %.3f--%.3f %s" %
                    (names[k], len(vs), st.mean(vs), BS, st.stdev(vs),
                     min(vs), max(vs), BS + BS))
    out.append(tbl(
        "tab:spdnet",
        "An independent SPD-manifold architecture, cohort A, mean $" + BS +
        "pm$ SD over 3 seeds. Removing alignment entirely costs 0.002, well "
        "inside the seed spread, so this architecture reproduces the finding "
        "of Section~" + BS + "ref{sec:rate} on a different backbone: the "
        "alignment stage is not what carries the performance.",
        "lrrl", "Variant & $n$ & Bal. acc. & Range", rows))

    # ---------------- merge experiment, 3 seeds
    a = agg(["merge.json"], lambda k: k.split("|")[1])
    names = {"PowerAttn-full": "stem $" + BS + "times$ attention (full)",
             "PowerAttn-noattn": bold("attention removed"),
             "PowerAttn-nopower": "power stem removed",
             "ShallowFBCSPNet": "ShallowFBCSPNet",
             "ATCNet": "ATCNet"}
    rows = []
    for k in ("PowerAttn-full", "PowerAttn-noattn", "PowerAttn-nopower",
              "ShallowFBCSPNet", "ATCNet"):
        if k not in a:
            continue
        vs = a[k]
        rows.append("%s & %d & %.3f $%spm$ %.3f & %.3f %s" %
                    (names[k], len(vs), st.mean(vs), BS, st.stdev(vs),
                     max(vs) - min(vs), BS + BS))
    out.append(tbl(
        "tab:merge",
        "Merging a power stem with a within-epoch attention block, cohort A, "
        "mean $" + BS + "pm$ SD over 3 seeds. Removing the attention block "
        "improves the merge by 0.024, so the block is not earning its place. "
        "Note also the per-seed spread of the published baselines, which "
        "reaches 0.053 and 0.041: this is the scale at which single-seed "
        "rankings become uninterpretable.",
        "lrrr", "Configuration & $n$ & Bal. acc. & Spread", rows))

    # ---------------- published decoders x normalisation mode
    d = L("published.json")
    models, modes = [], ["perwindow", "global", "none"]
    tab = {}
    for k, v in d.items():
        a_ = acc(v)
        if a_ is None:
            continue
        p = k.split("|")
        m, mode = p[1], p[2]
        tab.setdefault(m, {})[mode] = a_
        if m not in models:
            models.append(m)
    rows = []
    for m in models:
        cells = []
        best = max((tab[m].get(x, -1) for x in modes))
        for mode in modes:
            v = tab[m].get(mode)
            cells.append("---" if v is None else
                         (bold("%.3f" % v) if v == best else "%.3f" % v))
        rows.append("%s & %s %s" % (m.replace("FBCSPNet", "FBCSPNet"),
                                    " & ".join(cells), BS + BS))
    out.append(tbl(
        "tab:pubnorm",
        "Amplitude-normalisation mode across seven published decoders, cohort "
        "A, single seed. Best per row in bold. Per-window normalisation is "
        "never the best choice and is the worst for four of the seven, which "
        "is the architecture-level counterpart of the representation-level "
        "dose--response in Table~" + BS + "ref{tab:norm}.",
        "lrrr", "Model & Per-window & Global & None", rows, small=True))

    # ---------------- amplitude shuffle control
    d = L("amp_ablation.json")
    tab = {}
    for k, v in d.items():
        a_ = acc(v)
        if a_ is None:
            continue
        p = k.split("|")
        tab.setdefault(p[1], {})[p[4]] = a_
    rows = []
    for m, r in tab.items():
        on, sh = r.get("amp-on"), r.get("amp-shuffle")
        if on is None or sh is None:
            continue
        rows.append("%s & %.3f & %.3f & %+.3f %s" %
                    (m, on, sh, sh - on, BS + BS))
    out.append(tbl(
        "tab:ampctrl",
        "Amplitude side-channel control, cohort A, single seed. "
        "\\textit{amp-on} supplies a per-window amplitude feature; "
        "\\textit{amp-shuffle} supplies the same feature with its window "
        "assignment permuted. Five of six models change by less than 0.01, so "
        "the feature carries almost no information beyond what the shuffled "
        "version already provides, and the side-channel was dropped.",
        "lrrr", "Model & amp-on & amp-shuffle & $" + BS + "Delta$", rows,
        small=True))

    # ---------------- feature representation x preprocessing
    d = L("features.json")
    reps = ["bandpower", "fbcsp", "tangent_ea", "plv", "tangent+plv"]
    pres = ["raw", "car", "laplacian"]
    rows = []
    for rep in reps:
        cells = []
        for pre in pres:
            v = d.get("%s|%s" % (pre, rep))
            a_ = acc(v)
            cells.append("---" if a_ is None else "%.3f" % a_)
        rows.append("%s & %s %s" % (rep.replace("_", BS + "_"),
                                    " & ".join(cells), BS + BS))
    out.append(tbl(
        "tab:features",
        "Feature representation against spatial preprocessing, cohort A, "
        "single seed. Entries marked --- did not converge (FBCSP fails on "
        "rank-deficient re-referenced covariances). The tangent-space "
        "representation is the strongest single family and is what motivates "
        "the covariance-based alignment stage.",
        "lrrr", "Representation & Raw & CAR & Laplacian", rows, small=True))

    # ---------------- architecture sweep
    d = L("arch_sweep.json")
    rows_all = []
    for k, v in d.items():
        if not isinstance(v, dict) or "mean" not in v:
            continue
        m = v["mean"]
        rows_all.append((m.get("bal_acc", 0), k, m.get("ece")))
    rows_all.sort(reverse=True)
    base = next((r for r in rows_all if r[1].startswith("00_")), None)
    rows = []
    for a_, k, e in rows_all[:8]:
        nm = k.split("_", 1)[1].replace("_", " ")
        d_ = "" if base is None else " & %+.3f" % (a_ - base[0])
        rows.append("%s & %.3f & %s%s %s" %
                    (nm, a_, "---" if e is None else "%.3f" % e, d_, BS + BS))
    if base:
        rows.append(BS + "midrule")
        rows.append("baseline & %.3f & %s & --- %s" %
                    (base[0], "---" if base[2] is None else "%.3f" % base[2],
                     BS + BS))
    out.append(tbl(
        "tab:archsweep",
        "Architecture sweep, cohort A: the eight best of 24 configurations "
        "against the baseline, single seed. No structural change reaches "
        "0.06 over the baseline, and widening the network (F16, F24) is worth "
        "less than changing the readout, which is why capacity scaling was "
        "rejected in Table~" + BS + "ref{tab:rejected}.",
        "lrrr", "Configuration & Bal. acc. & ECE & $" + BS + "Delta$", rows,
        small=True))

    OUT.write_text("".join(out), encoding="utf-8")
    print("wrote %s (%d tables)" % (OUT.name, len(out) - 1))


if __name__ == "__main__":
    main()
